[package]
name = "fides"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Fides is a library for hashing and symmetric/asymmetric cryptography written in Rust."
repository = "https://github.com/stelar-software/rust-fides"
readme = "README.md"

[dependencies]